name: tui
version: 0.0.0.0
github: 'NorfairKing/tui'
license: MIT

library:
  source-dirs: src
  dependencies:
    - base >= 4.7 && < 5
    - brick
    - vty
    - directory
    - cursor
    - http-listen
    - safe
    - bytestring
    - text
    - classy-prelude
    - Hclip
    - deepseq
    - unliftio
    - silently
    - typed-process >= 0.2.6.0

executables:
  tui:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - base >= 4.7 && < 5
      - tui
